### ISSUE TITLE
wiki連結有誤所以抓不到鄉鎮資料

### ISSUE THREAD

**Issue by alanyeh20001** [Unayung/taiwan_city_dists_helper#3]
跑 `rake taiwan_city_dists_helper:get_cities_and_dists` 這行指令時一直出現「沒有連接網路」的錯誤，但我確定路是暢通的。
後來發現wiki的連結為https開頭，而rake裡面的連結為http開頭。
手動測試下面的程式碼
`doc = Nokogiri::HTML(open(url))` url代入的是原本的http wiki連結，結果出現以下：

`RuntimeError: redirection forbidden: http://zh.wikipedia.org/wiki/%E4%B8%AD%E8%8F%AF%E6%B0%91%E5%9C%8B%E5%8F%B0%E7%81%A3%E5%9C%B0%E5%8D%80%E9%84%89%E9%8E%AE%E5%B8%82%E5%8D%80%E5%88%97%E8%A1%A8 -> https://zh.wikipedia.org/wiki/%E4%B8%AD%E8%8F%AF%E6%B0%91%E5%9C%8B%E5%8F%B0%E7%81%A3%E5%9C%B0%E5%8D%80%E9%84%89%E9%8E%AE%E5%B8%82%E5%8D%80%E5%88%97%E8%A1%A8`

所以可能是要更新http至https，麻煩 @Unayung 幫忙看一下了謝謝：）

**Comment by Unayung** [comment]
感謝回報，放置超久XD
